### ISSUE TITLE
White borders around images

### ISSUE THREAD

**Issue by FM-96** [pdgwien/mtg-emblems#19]
There are white borders visible around (at least some of) the images when they are not on a white background.
![screenshot_2015-02-11-05-53-59](https://cloud.githubusercontent.com/assets/4470619/6142284/d9f1da4a-b1b3-11e4-8a40-399577c3a8b7.png)

**Comment by pdgwien** [comment]
Might hopefully be fixed, when I change the icons to SVG.

**Comment by sockpuppetcow** [comment]
Nope. https://www.dropbox.com/s/c9r6zfnibtkez5i/Screenshot_2015-02-16-11-23-57.png?dl=0

**Comment by pdgwien** [comment]
…

The newest build hasn't been build yet, so in the meanwhile the old version is still online.

**Comment by FM-96** [comment]
I thought you said it builds automatically with each commit?

**Comment by pdgwien** [comment]
Wow, can no one around here read a damn badge? 
![screenshot 2015-02-16 18 40 45](https://cloud.githubusercontent.com/assets/1881000/6216539/89e52bae-b60b-11e4-86c2-212d310bb6b4.png)

**Comment by pdgwien** [comment]
Remember, green is good, red is bad…
![screenshot 2015-02-16 19 21 08](https://cloud.githubusercontent.com/assets/1881000/6217145/275cfd44-b611-11e4-83ed-9f3e53e808c1.png)
