### ISSUE TITLE
"{C}" is now the colorless mana symbol

### ISSUE THREAD

**Issue by FM-96** [pdgwien/mtg-emblems#21]
As of Oath of the Gatewatch, colorless mana and generic mana are represented by different symbols.

"{C}" was until now the Chaos symbol used in Planechase, but now it is the colorless mana symbol ([looking like this](http://i.imgur.com/HaffTAV.png)).

The chaos symbol is now "CHAOS", according to the Oracle.

Seeing as one of the emblems now uses the colorless mana symbol, this should be corrected.

**Comment by pdgwien** [comment]
Ok, I'll update the sprites as soon as I find a svg version of the colorless mana symbol.
