### ISSUE TITLE
Make "online multiplayer" version

### ISSUE THREAD

**Issue by pdgwien** [pdgwien/mtg-emblems#8]
Basically, I want to be able to give people an URL to be able to watch all the emblems as they are getting played. That way there is no needed trust when you play for example over Cockatrice.

I'm however unsure how to do it. Should everyone be able to play Emblems, or should one person be the host while the others only can watch.

If everybody can play emblems, there is the problem of emblem pool synchronisation, I might have to introduce IDs to the emblems and rewrite the emblem picking, which would probably be a good idea anyway. The code is quite messy...

**Comment by FM-96** [comment]
Introducing IDs would make adding new emblems more complicated though, wouldn't it?

**Comment by pdgwien** [comment]
Well, you copy the last emblem, increment the ID and change the rest to make a new emblem, not *that* hard.

However, if we had like a host/watcher-situation, that would probably be not needed.

**Comment by FM-96** [comment]
Host/Watcher seems sufficient.

**Comment by pdgwien** [comment]
Closed in b8a3fa7
