### ISSUE TITLE
Write text in brackets in italics

### ISSUE THREAD

**Issue by FM-96** [pdgwien/mtg-emblems#9]
Reminder text is always italicized in MtG. *(Any text in brackets is reminder text.)*

**Comment by pdgwien** [comment]
I guess the right way to do this is to add some kind of tag. That way we can also italicize keywords.

**Comment by FM-96** [comment]
So, what tag should we choose then? Just <i>?

**Comment by pdgwien** [comment]
I was thinking about about Markdown-like tags, so * * for italics.
